# Generated by Django 4.2.6 on 2023-10-23 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('symbols', models.CharField(max_length=1000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('symbol_id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserListMapping',
            fields=[
                ('user_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.lists')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.IntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal.symbol')),
            ],
            options={
                'unique_together': {('date', 'symbol')},
            },
        ),
    ]
